### ISSUE TITLE
store metadata in generated images

### ISSUE THREAD

**Issue by damiencourousse** [LaurentRDC/hakyll-images#5]
Image metadata are not preserved through image transformations.
For instance, it would be nice to read/store image orientation.

**Comment by LaurentRDC** [comment]
Is this something that is usually stored in file metadata, or is this file-format specific?

**Comment by damiencourousse** [comment]
I need image orientation info.  In my use case, this information is stored in the image.
```
$ exiftool images/IMG_6140.JPG | grep Orientation
Orientation                     : Rotate 90 CW
```

**Comment by damiencourousse** [comment]
For the sake of documenting this, in case other users meet the same need.  

My workaround is to use imagemagick's binary `convert`.  However, I am not happy with this solution because it is hacky, and because it relies on an external dependency (`convert`) that I cannot describe in cabal/stack configuration.

```
resizeCompiler :: Width -> Height -> Compiler (Item ())
resizeCompiler w h = do
  -- MAYBE.  check if input is an image.
  input <- getUnderlying
  output <- getRoute input >>= \case
    Just o -> return o
    Nothing -> fail $ "ERROR - route not found for" ++ show input
  siteRoot <- destinationDirectory . compilerConfig <$> compilerAsk

  unsafeCompiler $ do
    let fullRoute = siteRoot </> makeRelative "/" output
        resizeDims :: String
        resizeDims = show w ++ "x" ++ show h

    createDirectoryIfMissing True $ takeDirectory fullRoute
    _ <- Process.readProcess "convert" [toFilePath input, "-resize", resizeDims, fullRoute] ""
    return $ Item input ()
```

**Comment by LaurentRDC** [comment]
Preserving file metadata, like in your example, presents some challenges. Hakyll takes care of deserialization and serialization, and in the case of serialization, I think all file metadata is lost, for all types of files.

However, getting file metadata during site compilation might be an option:

```
hakyll $ do
    ...        
    match jpgImages $ do
        route   idRoute
        compile $ do
            meta <- getExifMetadata
            loadImage 
                >>= doSomethingWithMetadata meta 
                >>= compressJpgCompiler 50
```

Let me know if this is something that is acceptable. Available picture metadata should be described in JuicyPixels's [Codec.Picture.Metadata](https://hackage.haskell.org/package/JuicyPixels/docs/Codec-Picture-Metadata.html) and [Codec.Picture.Metadata.Exif](https://hackage.haskell.org/package/JuicyPixels/docs/Codec-Picture-Metadata-Exif.html) modules. Otherwise, I'm open to pull requests

**Comment by damiencourousse** [comment]
Yes, this is more about a feature request than an issue per se.
I tried to sketch something in hakyll-images to see what it would look like, but this feature would maybe require extensive changes.  Also, JuicyPixel supports a limited subset of Exif metadata AFAII (for image encoding, at least).

Hakyll's `CopyFile`s does preserve metadata.  If exif info is encoded in the image file, it is still present in the deployed image after site building.  Also, system metadata (permissions, etc.) will be preserved if Hakyll is built with the package directory in version 1.2.6 or above ([here](https://hackage.haskell.org/package/hakyll-4.12.5.2/docs/src/Hakyll.Core.File.html#CopyFile)).

**Comment by damiencourousse** [comment]
> Preserving file metadata, like in your example, presents some challenges. Hakyll takes care of deserialization and serialization, and in the case of serialization, I think all file metadata is lost, for all types of files.
> 
> However, getting file metadata during site compilation might be an option:
> 
> ```
> hakyll $ do
>     ...        
>     match jpgImages $ do
>         route   idRoute
>         compile $ do
>             meta <- getExifMetadata
>             loadImage 
>                 >>= doSomethingWithMetadata meta 
>                 >>= compressJpgCompiler 50
> ```
> 
> Let me know if this is something that is acceptable. 


Yes, that could be interesting.
To support this, `Image` would probably need to be defined as something like:
```
data Image = Image { format :: ImageFormat
                   , image :: ByteString
                   , metadata :: Metadata
                   }
    deriving (Typeable)
```

JuicyPixel pretty well supports the decoding of images with metadata, but in any case the main bottleneck will be the re-encoding of metadatas.

Your library is really interesting and pretty useful anyway! :)

**Comment by LaurentRDC** [comment]
Turns out that metadata is encoded in the bytestring of the image, so I didn't have to change the `Image` type at all.

Release 0.4.4 adds the following compiler:

```haskell
-- | Extract metadata from an image.
--
-- @
-- match "*.jpg" $ do
--     route idRoute
--     compile $ do
--         im <- loadImage
--         meta <- imageMetadata
--         doSomethingWithMetadata meta
--         ...
-- @
imageMetadata :: Item Image -> Compiler Metadatas
```
where the `Metadatas` type is re-exported from [`Codec.Picture.Metadata`](https://hackage.haskell.org/package/JuicyPixels/docs/Codec-Picture-Metadata.html).

Exif metadata is part of the `Metadatas` datatype. You will be able to make your own Hakyll compiler that extract Exif metadata specifically.

I will close this for now. If you find that this doesn't quite work for you, feel free to re-open it!

**Comment by ghost** [comment]
Hi @LaurentRDC !
I have a problem when trying to use imageMetadata compiler
```
site.hs:19:1: error:
    Could not load module ‘Hakyll.Images.Metadata’
    it is a hidden module in the package ‘hakyll-images-0.4.4’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
19 | import Hakyll.Images.Metadata
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by LaurentRDC** [comment]
Hi there,

I can see that the contents of that module are re-exported in the main `Hakyll.Images` module, but I didn't expose it by mistake. For now, you can take a look at the documentation here to import what you need from `Hakyll.Images`:

http://hackage.haskell.org/package/hakyll-images-1.0.0/docs/Hakyll-Images.html

I will release a small update that exports the `Hakyll.Images.Metadata` module explicitly in the next hour.

**Comment by LaurentRDC** [comment]
Ok the [new version is live](http://hackage.haskell.org/package/hakyll-images-1.0.1) with the `Hakyll.Images.Metadata` module exposed.
