### ISSUE TITLE
my build fails

### ISSUE THREAD

**Issue by mherzl** [LaurentRDC/hakyll-images#7]
Hello LaurentRDC, I cloned and tried to build `hakyll-images`, but get a `Process exited with exit code ExitFailure 1` error while building package `digest`. 

```
data-default-class               > Registering library for data-default-class-0.1.2.0..
colour                           > [14 of 14] Compiling Data.Colour.CIE
colour                           > copy/register
colour                           > Installing library in /home/matthew/.stack/snapshots/x86_64-linux-nix/50fe087c1f58178f49afa0289a8b3aa92f948aace525bcc9d294ee4135f30ad1/8.4.4/lib/x86_64-linux-ghc-8.4.4/colour-2.3.4-C3PVIHDZkyCIpOJGl3M0hE
colour                           > Registering library for colour-2.3.4..
cmark-gfm                        > copy/register
cmark-gfm                        > Installing library in /home/matthew/.stack/snapshots/x86_64-linux-nix/50fe087c1f58178f49afa0289a8b3aa92f948aace525bcc9d294ee4135f30ad1/8.4.4/lib/x86_64-linux-ghc-8.4.4/cmark-gfm-0.1.6-9EnbdkMqo0w1MQ5yjELst5
cmark-gfm                        > Registering library for cmark-gfm-0.1.6..
                          
--  While building package digest-0.0.1.2 using:
...
    Process exited with code: ExitFailure 1
Progress 20/153
```

Does the build succeed for you? I'm wondering if some dependency might be missing from the code or something. Alternatively maybe something is missing on my machine and thus the problem is not in the code code I cloned down; (I am still learning nixos and maybe missed something related to that). Thanks!

**Comment by LaurentRDC** [comment]
Hello Matthew,

I just ran automated tests again [here](https://ci.appveyor.com/project/LaurentRDC/hakyll-images/builds/31339810) and everything builds fine. Same on my machine, with a fresh clone. 

Which stack resolver are you using?

**Comment by mherzl** [comment]
Okay, sounds like the problem is on my end then. For stack resolver I just have the `resolver: lts-12.26` specified in the repo's `stack.yaml`.

Thanks for the response! I'm guessing there's some nixos thing I'll have to sort out to get it working.

**Comment by mherzl** [comment]
Yep it was a nixos thing. The package built successfully once I added the following to `stack.yaml`:

```
nix:
  enable: true
  packages:
    - zlib
```
