### ISSUE TITLE
Only compress large images?

### ISSUE THREAD

**Issue by tbenst** [LaurentRDC/hakyll-images#8]
Due to migrating from an older Blog, I have some older images that are already compressed, and newer images in their original, several MB glory. Is there a straightforward way to only compress images larger than say 500KB as to avoid needless lossy recompression? I see by using [imageMetadata](http://hackage.haskell.org/package/hakyll-images-1.0.1/docs/Hakyll-Images-Metadata.html) that it should be straightforward to filter based on image dimension, but wasn’t sure how to got about based on size.

many thanks!

**Comment by LaurentRDC** [comment]
Hi there,

You can match only "large" images using the [`matchMetadata`](https://hackage.haskell.org/package/hakyll-4.13.4.1/docs/Hakyll-Core-Rules.html#v:matchMetadata) function from `hakyll`. 

I imagine something like that:

```haskell
largeImage :: Metadata -> Bool
largeImage = ...

smallImage :: Metadata -> Bool
smallImage = not . largeImage

hakyll $ do
    (...)

    -- Large images get compressed
    matchMetadata "images/*.jpg" largeImage $ do
       route idRoute
       compile $ loadImage
           >>= compressJpgCompiler 50

    -- Small images are copied
    matchMetadata "images/*.jpg" smallImage $ do
       route idRoute
       compile copyFileCompiler
```

In this case, the [`Metadata` type is the one from `hakyll`](https://hackage.haskell.org/package/hakyll-4.13.4.1/docs/Hakyll-Core-Metadata.html#t:Metadata). I do not know what it will look like for your files.

**Comment by LaurentRDC** [comment]
The following would probably be simpler actually:

```haskell
import qualified Hakyll.Images.Metadata as M

imageSize :: M.Metadatas -> Word
imageSize m = height * width
    where
        width  = fromMaybe 1 $ M.lookup M.Width m
        height = fromMaybe 1 $ M.lookup M.Height m

hakyll $ do
    (...)
    match "images/*.jpg" $ do
        route   idRoute
        compile $ do
            i <- loadImage
            s <- imageSize <$> M.imageMetadata i
            if s > (320*320) 
                then compressJpgCompiler 50 i
                else return i
```

**Comment by tbenst** [comment]
Thank you for the very generous response! I was stuck since I fixated on the size in bytes which isn’t exposed by metadata, but I think in practice my large image files are also high resolution, and so this should work nicely :)

**Comment by tbenst** [comment]
settled on:
```haskell
    match "images/*.jpg" $ do
        route   idRoute
        compile $ do
            i <- loadImage
            s <- imageSize <$> M.imageMetadata i
            if s > (1024*1024)
                then do scaleImageCompiler 1024 1024 i
                    >>= compressJpgCompiler 80
                else return i
```

Thanks again!
